### ISSUE TITLE
 problem: "enter/return"

### ISSUE THREAD

**Issue by AdsonBatista** [chrokh/csharp-build-singlefile-sublime-text-2#7]
Hello, I'm learning C#. In my program the "enter" key not works in terminal. 

I'm use a MacOs and Sublime 3.

```
using System;

namespace variaveis
{
    class Program
    {
        static void Main(string[] args)
        {
            string firstName = "John";
            string lastName = "Doe";

            Console.WriteLine("Name: " + firstName + " " + lastName);

            Console.WriteLine("Please enter a new first name:");
            firstName = Console.ReadLine();

            Console.WriteLine("New name: " + firstName + " " + lastName);

            Console.ReadLine();
        }
    }
}
```

**Comment by chrokh** [comment]
Hi :)

I'm not sure it's possible to support input in the "bottom panel" (not sure what it's actually called) of Sublime. My assumption was that it's output only. However, please do correct me if I'm wrong.

I'd suggest running a terminal separately and simply compile and then run the compiled output. So on Mac OS e.g.:

```bash
$ mcs Program.cs         # First compile
$ mono Program.exe     # Then run
```

And to run the program if it successfully compiled then you can connect the two statements with an and, like so:

```bash
$ mcs Program.cs && mono Program.exe
```

And on Windows you do something like:
```cmd
csc.exe Program.cs
Program.exe
```
